apiVersion: v1
kind: Service
metadata:
  name: ai-ops-backend
  namespace: ai-ops
  labels:
    app: ai-ops-backend
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
      protocol: TCP
      name: http
  selector:
    app: ai-ops-backend
