apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-liveness-failure
  namespace: unhealthy-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-liveness
  template:
    metadata:
      labels:
        app: test-liveness
    spec:
      containers:
        - name: web
          image: nginx:alpine
          livenessProbe:
            httpGet:
              path: /this-path-does-not-exist
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
