apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-imagepull
  namespace: image-pull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-imagepull
  template:
    metadata:
      labels:
        app: test-imagepull
    spec:
      containers:
        - name: app
          image: nginx:this-tag-is-completely-fake-123
